# render.yaml - Render Blueprint
services:
  # Frontend Service (Next.js)
  - type: web
    name: sui-millionaire-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_WS_URL
        fromService:
          type: web
          name: sui-millionaire-websocket
          property: url
        # Sẽ tự động thay https bằng wss
        transform: |
          return value.replace('https://', 'wss://');
    healthCheckPath: /
    
  # WebSocket Service
  - type: web
    name: sui-millionaire-websocket
    runtime: node
    buildCommand: npm install
    startCommand: node server/websocket-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  # Render mặc định
    healthCheckPath: /health  # Cần thêm health endpoint

databases: []  # Không cần database hiện tại

envVarGroups: []