services:
  - type: web
    name: sui-millionaire-websocket
    runtime: node
    buildCommand: npm install
    startCommand: node server/websocket-server.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health

  - type: web
    name: whoissuimillioner
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_WS_URL
        value: wss://whoissuimillioner.onrender.com
    healthCheckPath: /

databases: []
envVarGroups: []